# Generated by Django 4.1.1 on 2022-09-16 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ("Category's Name", models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ("Currency's name", models.CharField(choices=[('DOLLARS', 'DOLLARS'), ('TAKA', 'TAKA'), ('UAE DIRHAM', 'UAE DIRHAM'), ('BITCOIN', 'BITCOIN'), ('JAPANIAN YEN', 'JAPANIAN YEN')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Time_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event Start Date', models.DateField(max_length=50)),
                ('start_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ("Venue's Name", models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=50)),
                ('Event Type', models.CharField(choices=[('In-person', 'In-person'), ('Streaming', 'Streaming'), ('In-person and streaming', 'In-person and streaming')], max_length=50)),
                ('Stream Type', models.CharField(choices=[('Secured Promotix', 'Secured Promotix'), ('Unsecured - Other', 'Unsecured - Other')], max_length=20)),
                ('Venue/Address name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Category', to='events.category')),
                ('time', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Time', to='events.time_schedule')),
            ],
        ),
    ]
