# Generated by Django 4.1.1 on 2022-09-17 01:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Ticket_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticket Name', models.CharField(max_length=50)),
                ('Ticket Type', models.CharField(max_length=50)),
                ('created_date', models.DateField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name="Person's Ticket Name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='time_schedule',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 17, 1, 57, 6, 368621, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Ticket_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_id', to='events.event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id', to='events.user')),
            ],
        ),
    ]
