# Generated by Django 4.1.1 on 2022-09-17 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', "0002_create_ticket_type_event_person's ticket name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='create_ticket_type',
            old_name='Ticket Name',
            new_name='ticket_name',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name="Currency's name",
            new_name='name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Event Type',
            new_name='event_type',
        ),
        migrations.RenameField(
            model_name='event',
            old_name="Person's Ticket Name",
            new_name='person_ticket_name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Stream Type',
            new_name='stream',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Venue/Address name',
            new_name='venue_or_address_name',
        ),
        migrations.RenameField(
            model_name='time_schedule',
            old_name='Event Start Date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Username',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='create_ticket_type',
            name='Ticket Type',
        ),
        migrations.AddField(
            model_name='create_ticket_type',
            name='type',
            field=models.CharField(choices=[('GA Ticket', 'GA Ticket'), ('VIP Ticket', 'VIP Ticket'), ('Reserved Seating', 'Reserved Seating'), ('Members-only Ticket', 'Members-only Ticket'), ('Giveaway Ticket', 'Giveaway Ticket'), ('Group Package Ticket', 'Group Package Ticket')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=100000, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='events.user'),
        ),
        migrations.AddField(
            model_name='ticket_booking',
            name='UID',
            field=models.PositiveIntegerField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket_booking',
            name='creation_date',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name='ticket_booking',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket_booking',
            name='image',
            field=models.ImageField(blank=True, max_length=300, upload_to='static/thumbnail/'),
        ),
        migrations.AddField(
            model_name='ticket_booking',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='ticket_booking',
            name='is_attend',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='ticket_booking',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket_booking',
            name='phone',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ticket_booking',
            name='ticket_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_id', to='events.create_ticket_type'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name="Category's Name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='create_ticket_type',
            name='created_date',
            field=models.DateField(auto_created=True, auto_now=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket_booking',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_id', to='events.event'),
        ),
        migrations.CreateModel(
            name='Volunteer_Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_created=True, auto_now=True, unique=True)),
                ('UID', models.PositiveIntegerField(auto_created=True, null=True, unique=True)),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('email', models.EmailField(max_length=100, null=True, unique=True)),
                ('phone', models.PositiveIntegerField(null=True, unique=True)),
                ('image', models.ImageField(blank=True, max_length=300, unique=True, upload_to='static/thumbnail/')),
                ('is_attend', models.BooleanField(null=True, unique=True)),
                ('is_active', models.BooleanField(null=True, unique=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id_1', to='events.user')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_date', models.DateField(auto_created=True, auto_now=True)),
                ('reason', models.TextField(max_length=1000, null=True)),
                ('demand_date', models.DateField(max_length=200)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_id_1', to='events.event')),
            ],
        ),
    ]
