# Generated by Django 4.1.1 on 2022-09-17 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_category_categorie_rename_currency_currencie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password2',
        ),
    ]
