# Generated by Django 4.1.1 on 2022-09-17 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_password1_user_password_remove_user_password2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name="Category's Name",
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='categorie',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name="Venue's Name",
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AlterField(
            model_name='refund',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_id_refund', to='events.event'),
        ),
        migrations.AlterField(
            model_name='volunteer_ticket',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id_volunteer_ticket', to='events.user'),
        ),
    ]
