# Generated by Django 4.1.1 on 2022-09-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', "0006_rename_category's name_categorie_category_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
