# Generated by Django 4.1.1 on 2022-09-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_payment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(default=models.CharField(max_length=50), max_length=100),
        ),
        migrations.AlterField(
            model_name='currencie',
            name='name',
            field=models.CharField(choices=[('usd', 'DOLLARS'), ('bdt', 'TAKA'), ('aed', 'UAE DIRHAM'), ('btc', 'BITCOIN'), ('jpy', 'JAPANIAN YEN')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.IntegerField(default=models.DecimalField(decimal_places=2, max_digits=1000000, null=True)),
        ),
    ]
