# Generated by Django 4.1.1 on 2022-09-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_payment_name_alter_currencie_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencie',
            name='name',
            field=models.CharField(choices=[('usd', 'Dollars'), ('bdt', 'Taka'), ('aed', 'UAE Dirham'), ('btc', 'Bitcoin'), ('jpy', 'Japanian Yen')], max_length=50),
        ),
    ]
