# Generated by Django 4.1.1 on 2022-09-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_event_event_type_alter_event_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencie',
            name='name',
            field=models.CharField(choices=[('usd', 'Dollars'), ('bdt', 'Taka'), ('aed', 'UAE Dirham'), ('kwd', 'Kuwait Dinar'), ('jpy', 'Japanian Yen')], default=('usd', 'Dollars'), max_length=50),
        ),
    ]
