# Generated by Django 4.1.1 on 2022-09-28 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0018_alter_currencie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_booking',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='volunteer_ticket',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id_volunteer_ticket', to=settings.AUTH_USER_MODEL),
        ),
    ]
