# Generated by Django 4.1.1 on 2022-10-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_alter_payment_name_alter_payment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='reason',
            field=models.CharField(choices=[('1', 'duplicate'), ('2', 'fraudulent'), ('3', 'requested_by_customer'), ('4', 'expired_uncaptured_charge')], max_length=25, null=True),
        ),
    ]
