# Generated by Django 4.1.1 on 2022-10-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_alter_refund_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(
                decimal_places=2, max_digits=99999999, null=True),
        ),
    ]
