# Generated by Django 4.1.1 on 2022-10-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_alter_create_ticket_type_type_alter_refund_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='venue_or_address_name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='venue_or_address_name_link',
            new_name='venue_or_address_name',
        ),
    ]
