# Generated by Django 4.1.1 on 2022-10-28 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_auto_20221028_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue_or_address_name_link',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_or_address_name', to='events.venue'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_or_address_name',
            field=models.CharField(max_length=100),
        ),
    ]
