# Generated by Django 4.1.1 on 2022-10-28 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_remove_event_venue_or_address_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='venue_or_address_name_link',
            new_name='venue_or_address_name',
        ),
    ]
