# Generated by Django 4.1.1 on 2022-10-28 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_rename_venue_or_address_name_link_event_venue_or_address_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=99999999),
        ),
        migrations.AlterField(
            model_name='event',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='venue',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
