# Generated by Django 4.0.5 on 2022-06-21 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
