# Generated by Django 4.0.5 on 2022-06-28 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='date_created',
        ),
    ]
